# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=32, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveIntegerField()),
                ('autopilot', models.CharField(max_length=16)),
                ('badge', models.CharField(max_length=16)),
                ('battery', models.CharField(max_length=16)),
                ('config_id', models.PositiveIntegerField()),
                ('decor', models.CharField(max_length=16)),
                ('destination_handling_fee', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('drive_train', models.PositiveIntegerField()),
                ('metro_id', models.PositiveSmallIntegerField()),
                ('model', models.CharField(max_length=16)),
                ('model_varient', models.CharField(max_length=16)),
                ('odometer', models.PositiveIntegerField()),
                ('odometer_type', models.CharField(max_length=16)),
                ('option_code_list', models.TextField()),
                ('option_code_list_with_price', models.TextField()),
                ('ownership_transfer_count', models.PositiveSmallIntegerField()),
                ('paint', models.CharField(max_length=16)),
                ('range', models.CharField(max_length=16)),
                ('roof', models.CharField(max_length=16)),
                ('title_status', models.CharField(max_length=16)),
                ('title_sub_status', models.TextField()),
                ('trade_in_type', models.CharField(blank=True, max_length=16, null=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('is_autopilot', models.BooleanField()),
                ('is_first_registration_date', models.BooleanField()),
                ('is_panoramic', models.BooleanField()),
                ('is_premium', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CarOdometerChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer_before', models.PositiveIntegerField()),
                ('odometer_new', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Car')),
            ],
        ),
        migrations.CreateModel(
            name='CarPriceChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_before', models.PositiveIntegerField()),
                ('price_new', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Car')),
            ],
        ),
    ]
