# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drive_train',
            field=models.CharField(max_length=16),
        ),
    ]
