# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161103_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='trade_in_type',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
    ]
