# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161125_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carodometerchange',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='carpricechange',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
